# --- BEGIN_KITTY_FONTS ---
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 	 13
# --- END_KITTY_FONTS ---

# --- KEYMAPS --- 
map ctrl+shift+[ show_scrollback
map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab

# --- NVIM_SCROLLBACK_PAGER ---
scrollback_pager nvim -c "Man!" -c "setlocal number relativenumber" -c "nnoremap q :qa!<CR>" -

# --- WINDOW LAYOUT ---
window_padding_width 	15
hide_window_decorations yes
remember_window_size 	no

# --- BEHAVIOR ---
enable_audio_bell 	no
disable_ligatures 	always

# --- CURSOR ---
cursor_shape 		beam
cursor_blink_interval 	0

# --- WAYLAND SPECIFIC ---
linux_display_server 	wayland

# --- TRANSPARENCY & BLUR ---
background_opacity 	 	0.8
background_blur 	 	1
scrollbar_handle_opacity 	0
scrollbar_track_opacity 	0
scrollbar_track_hover_opacity 	0

# --- BEHAVIOR ---
confirm_os_window_close 0

# --- PERFORMANCE & LATENCY TUNING ---
input_delay 	1
sync_to_monitor no

# --- STOP DRAWING CELLS TEXT ---
resize_debounce_time 0

# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
