$image = {{image}}
<* for name, value in colors *>
${{name}} = rgba({{value.default.hex_stripped}}ff)
<* endfor *>

$surface_container_lowest_transparent_80 = rgba({{colors.surface_container_lowest.default.hex_stripped}}cc)
